Feat/state
Lagrange-Labs/Euclid-database pull request #7
Opened 2024-06-11 11:46 UTC by nikkolasg

2024-06-13 11:09 UTC, nicholas-mainardi requested changes

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/storage/leaf.rs
I think we are no longer using this "LEAF" domain separator when computing hashes (e.g., it is not used in query2 storage leaf circuit). So hashing it in this way might lead to a mismatch with what we computed in pre-processing?

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/storage/public_inputs.rs
> +        U256::from_little_endian(&convert_u32_fields_to_u8_vec(self.query_results_raw()))
Reminder: once we merge here PR introducing Uint256Target, we should replace this with the method `convert_u32_fields_to_u256` introduced in that PR

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/storage/public_inputs.rs
> +        U256::from_little_endian(&convert_u32_fields_to_u8_vec(self.query_rewards_rate_raw()))
Same as above: reminder to replace this with `convert_u32_fields_to_u256` method

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/storage/tests.rs
>      let exp_c = hash_n_to_hash_no_pad::<_, PoseidonPermutation<_>>(&inputs);
Shouldn't we use the functions we expose for dist system (i.e., `leaf_hash_for_mapping`) to recompute the hash in the test?

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/state/mod.rs
> +        BlockPublicInputs::register(cb, b, r, &block_leaf_hash, &a, &x, m, s, v, rewards);
The length slot `s` shouldn't be in the public inputs for this query, as it is a dummy value

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/state/mod.rs
>  const NUM_STORAGE_INPUTS: usize = StorageInputs::<Target>::TOTAL_LEN;
Shouldn't we port also to `assign` function the changes done [in this PR](https://github.com/Lagrange-Labs/Euclid-database/pull/3/files#diff-aae553704e9f125565851969da131ff682677dccd65ab226d4ee94456f7e109aR239) for state query2 circuit?

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/state/tests.rs
> +
Why not usign `pack().to_fields` to get `user_address_fields` from `left_pad32(user_address.as_fixed_bytes())`?

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/state/tests.rs
>          let depth = GoldilocksField::from_canonical_u32(MAX_DEPTH as u32);
Shouldn't we test also a smaller depth than `MAX_DEPTH`? Should be similar to what was done [in this PR](https://github.com/Lagrange-Labs/Euclid-database/pull/3/files#diff-692d4c688223ce4607abc5e1e5b010b19d85eb4f27533aa274ea0fb9280b56a0R134)

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/state/tests.rs
Wouldn't it be better here to use `state_leaf_hash` and `state_node_hash` methods to compute the state root?

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/block/full_node.rs
> +        let new_range_length = b.sub(new_upper_block, new_range_min_bound);
Don't we save one operation if we just sum the `inputs[0].range()` and `inputs[1].range()`? The result should be the same

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/revelation/public_inputs.rs
> +        8,
Better use constants here, no?

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/revelation/public_inputs.rs
> +impl<'a> RevelationPublicInputs<'a, GoldilocksField> {
Isn't this implementation redundant w.r.t. the implementation of `RevelationPublicInputs<'a, T>` for generic `T`?

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/revelation/circuit.rs
> +        let computed_min_block = b.sub(root_proof.block_number(), root_proof.range());
Isn't `computed_min_block == root_proof.block_number - root_proof.range +1`? If we included blocks up to N, and we included R blocks, then the first block being included should be `N-R+1`, no?

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/revelation/mod.rs
> +        query2_block_proof: Vec<u8>,
Rename query2 variables to query to avoid ambiguities?

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/revelation/circuit.rs
> +}
Shoudl we add some unit tests for the revelation circuit? Like to test cases where `query_min` and `query_max` are bigger then the oldest and latest block in block DB?

2024-06-13 11:09 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/api.rs
> +pub struct PublicParameters<const BLOCK_DB_DEPTH: usize, const L: usize> {
`L` should be no longer used for this query I think

2024-06-14 12:05 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/storage/public_inputs.rs
> +        U256::from_little_endian(&convert_u32_fields_to_u8_vec(self.query_results_raw()))
Resolving, done in PR #11

2024-06-14 12:06 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/storage/public_inputs.rs
> +        U256::from_little_endian(&convert_u32_fields_to_u8_vec(self.query_rewards_rate_raw()))
Resolving, done in PR #11

2024-06-14 12:06 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/state/mod.rs
> +        BlockPublicInputs::register(cb, b, r, &block_leaf_hash, &a, &x, m, s, v, rewards);
No longer needed since we need to have uniform public inputs between this circuit and query2

2024-06-14 12:07 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/api.rs
> +pub struct PublicParameters<const BLOCK_DB_DEPTH: usize, const L: usize> {
Resolving it since now we need to keep it since the public inputs have to be the same of query2

2024-06-14 16:24 UTC, nikkolasg commented on mr-plonky2-circuits/src/query_erc20/storage/leaf.rs
Sounds good, let's remove it. I just copied the file, let's just make sure we use the same hashing technique for sure. well spotted !

2024-06-14 20:46 UTC, nikkolasg commented on mr-plonky2-circuits/src/query_erc20/revelation/circuit.rs
> +        let computed_min_block = b.sub(root_proof.block_number(), root_proof.range());
Done

2024-06-14 20:54 UTC, nicholas-mainardi commented on mr-plonky2-circuits/src/query_erc20/state/tests.rs
>          let depth = GoldilocksField::from_canonical_u32(MAX_DEPTH as u32);
Added test with depth less than `MAX_DEPTH`

2024-06-14 22:22 UTC, merged